### ISSUE TITLE
Please retain the original pysaucenao licensing

### ISSUE THREAD

**Issue by FujiMakoto** [nomnoms12/saucenao_api#1]
Hello!

I see you are using the pysaucenao projects code for this API wrapper.

You are absolutely free to do so, but I must request that you retain the original projects licensing and copyright.

https://github.com/FujiMakoto/pysaucenao/blob/master/LICENSE

**Comment by nomnoms12** [comment]
@FujiMakoto, hello!

I'm sorry I didn't do it sooner; I'm not good at licensing. I changed the license and added your copyright. I also added a mention of your repository in README. Did I do it right? What else can I do to preserve the license and your rights?

*\_\_init\_\_.py:*
```python
__author__ = 'nomnoms12'
__copyright__ = 'Copyright 2020, Taiga.sh Development'
__credits__ = ['nomnoms12', 'FujiMakoto']
__license__ = 'GNU General Public License v3.0'
```
*README.md:*
> This package is based on [pysaucenao](https://github.com/FujiMakoto/pysaucenao).

**Comment by FujiMakoto** [comment]
That's plenty, thank you, and thank you for the quick response!
