### ISSUE TITLE
Can we use this with videos?

### ISSUE THREAD

**Issue by sanidhya711** [nomnoms12/saucenao_api#6]
i though so because it has the option called frame
??

**Comment by nomnoms12** [comment]
@sanidhyajain1, hi! Thanks for the good question!

**No**, we can't use SauceNao with videos. But we can use it with image formats that support animation, such as [GIF](https://en.wikipedia.org/wiki/GIF) and [WebP](https://en.wikipedia.org/wiki/WebP). The `frame` parameter indicates a specific frame from the file that will be searched.

Example:
```python
from saucenao_api import SauceNao

with open('image.gif', 'rb') as f:
    result = SauceNao(frame=46).from_file(f)[0]
```

BTW, the image can be: gif, jpg, png, bmp, svg, or webp.
