### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by khoadng** [nomnoms12/saucenao_api#9]
Got this error when running this code snippet

**Error**
```
Exception has occurred: BadKeyError
Invalid API key
  File "C:\Users\Admin\Projects\test.py", line 4, in <module>
    results = sauce.from_url('https://i.imgur.com/oZjCxGo.jpg')  # or from_file()
```

**Code**
```python
from saucenao_api import SauceNao

sauce = SauceNao()
results = sauce.from_url('https://i.imgur.com/oZjCxGo.jpg')  # or from_file()

best = results[0]  # results sorted by similarity
print(best.author)
```

Do I need to provide an API key or something?

**Comment by nomnoms12** [comment]
The error occurred because the server returned an HTTP 403 Forbidden response:
```python
{'header': {'status': -1, 'message': 'The anonymous account type does not permit API usage.'}}
```
SauceNao probably no longer supports anonymous requests, and **yes, you will have to register and pass an API key** with every request. (With the key, the request is successful.)

**Comment by nomnoms12** [comment]
@khoadng You have to pass the API key to the `SauceNao` class:
```python
# Replace the key with your own
sauce = SauceNao('077f16b38a2452401790540f41246c7d951330c0')
```
To get the key, register using the link: https://saucenao.com/user.php?page=search-api

**Comment by nomnoms12** [comment]
I think this can't be considered a bug in the library. If SauceNao's policy doesn't change in the next few days, I'll make `api_key` a required parameter and update the examples.

**Comment by khoadng** [comment]
Other than this, everything works flawlessly. Nice work!
Thanks for this awesome library.
